apiVersion: apps/v1
kind: Deployment
metadata:
  name: stunner-auth
spec:
  selector:
    matchLabels:
      app: stunner-auth
  replicas: 1
  template:
    metadata:
      labels:
        app: stunner-auth
    spec:
      containers:
      - name: stunner-auth-server
        image: docker.io/library/authhandler6:latest
        # imagePullPolicy: Never
       #  imagePullPolicy: Always
        command: [ "/go/src/authhandler" ]
        env:
        - name: STUNNERD_CONFIG_PATH
          value: "/etc/stunnerd/"
        volumeMounts:
        - name: stunnerd-config-volume
          mountPath: /etc/stunnerd
          readOnly: true
      volumes:
        - name: stunnerd-config-volume
          configMap:
            name: stunnerd-config
            optional: true

---
apiVersion: v1
kind: Service
metadata:
  name: stunner-auth
  labels:
    app: stunner-auth
spec:
  selector:
    app: stunner-auth
  ports:
    - port: 8080
      name: authhandler-tcp
  type: ClusterIP
