apiVersion: apps/v1
kind: Deployment
metadata:
  name: stunner-auth
  namespace: stunner
spec:
  selector:
    matchLabels:
      app: stunner-auth
  replicas: 1
  template:
    metadata:
      labels:
        app: stunner-auth
    spec:
      containers:
      - name: stunner-auth-server
        # image: l7mp/stunner-auth-service
        # imagePullPolicy: IfNotPresent
        image: localhost/l7mp/stunner-auth-service
        imagePullPolicy: Never
        command: [ "/stunner-auth-server" ]
        args: ["--verbose","--watch"]
        env:
        - name: STUNNERD_CONFIG_PATH
          value: "/etc/stunnerd/stunnerd.conf"
        volumeMounts:
        - name: stunnerd-config-volume
          mountPath: /etc/stunnerd
          readOnly: true
      volumes:
        - name: stunnerd-config-volume
          configMap:
            name: stunnerd-config
            optional: true

---
apiVersion: v1
kind: Service
metadata:
  name: stunner-auth
  namespace: stunner
  labels:
    app: stunner-auth
spec:
  selector:
    app: stunner-auth
  ports:
    - port: 8080
      name: stunner-auth-server
  type: ClusterIP
